// Blizzard's generated ScriptObject table names are implementation identifiers.
// These public widget names follow the mapping used by Ketho/vscode-wow-api.
const WIDGET_NAMES = {
  AbbreviateConfigAPI: 'AbbreviateConfig',
  FrameAPIArchaeologyDigsite: 'ArchaeologyDigSiteFrame',
  FrameAPIArchaeologyDigSiteFrame: 'ArchaeologyDigSiteFrame',
  FrameAPIBlob: 'Blob',
  FrameAPICharacterModelBase: 'CharacterModelBase',
  FrameAPICinematicModel: 'CinematicModel',
  FrameAPICooldown: 'Cooldown',
  FrameAPIDressUpModel: 'DressUpModel',
  FrameAPIFogOfWarFrame: 'FogOfWarFrame',
  FrameAPIModelSceneFrame: 'ModelScene',
  FrameAPIModelSceneFrameActor: 'ModelSceneActor',
  FrameAPIModelSceneFrameActorBase: 'ModelSceneActorBase',
  FrameAPINamePlate: 'NamePlate',
  FrameAPIQuestPOI: 'QuestPOIFrame',
  FrameAPIScenarioPOI: 'ScenarioPOIFrame',
  FrameAPISimpleCheckout: 'SimpleCheckout',
  FrameAPITabardModel: 'TabardModel',
  FrameAPITabardModelBase: 'TabardModelBase',
  FrameAPITooltip: 'GameTooltip',
  FrameAPIUnitPositionFrame: 'UnitPositionFrame',
  HousingCatalogSearcherAPI: 'HousingCatalogSearcher',
  HousingFixturePointFrameAPI: 'HousingFixturePointFrame',
  HousingLayoutPinFrameAPI: 'HousingLayoutPinFrame',
  LuaColorCurveObjectAPI: 'ColorCurveObject',
  LuaCurveObjectAPI: 'CurveObject',
  LuaCurveObjectBaseAPI: 'CurveObjectBase',
  LuaDurationObjectAPI: 'DurationObject',
  MinimapFrameAPI: 'Minimap',
  PingPinFrameAPI: 'PingPin',
  SimpleAnimAlphaAPI: 'Alpha',
  SimpleAnimAPI: 'Animation',
  SimpleAnimatableObjectAPI: 'AnimatableObject',
  SimpleAnimFlipBookAPI: 'FlipBook',
  SimpleAnimGroupAPI: 'AnimationGroup',
  SimpleAnimPathAPI: 'Path',
  SimpleAnimRadialProgressAPI: 'RadialProgress',
  SimpleAnimRotationAPI: 'Rotation',
  SimpleAnimScaleAPI: 'Scale',
  SimpleAnimScaleLineAPI: 'LineScale',
  SimpleAnimTextureCoordTranslationAPI: 'TextureCoordTranslation',
  SimpleAnimTranslationAPI: 'Translation',
  SimpleAnimTranslationLineAPI: 'LineTranslation',
  SimpleAnimVertexColorAPI: 'VertexColor',
  SimpleBrowserAPI: 'Browser',
  SimpleButtonAPI: 'Button',
  SimpleCheckboxAPI: 'CheckButton',
  SimpleColorSelectAPI: 'ColorSelect',
  SimpleControlPointAPI: 'ControlPoint',
  SimpleEditBoxAPI: 'EditBox',
  SimpleFontAPI: 'Font',
  SimpleFontStringAPI: 'FontString',
  SimpleFrameAPI: 'Frame',
  SimpleFrameScriptObjectAPI: 'FrameScriptObject',
  SimpleHTMLAPI: 'SimpleHTML',
  SimpleLineAPI: 'Line',
  SimpleMapSceneAPI: 'SimpleMap',
  SimpleMaskTextureAPI: 'MaskTexture',
  SimpleMessageFrameAPI: 'MessageFrame',
  SimpleModelAPI: 'Model',
  SimpleModelFFXAPI: 'ModelFFX',
  SimpleMovieAPI: 'MovieFrame',
  SimpleObjectAPI: 'Object',
  SimpleOffScreenFrameAPI: 'OffScreenFrame',
  SimpleRegionAPI: 'Region',
  SimpleScriptRegionAPI: 'ScriptRegion',
  SimpleScriptRegionResizingAPI: 'ScriptRegionResizing',
  SimpleScrollFrameAPI: 'ScrollFrame',
  SimpleSliderAPI: 'Slider',
  SimpleStatusBarAPI: 'StatusBar',
  SimpleTextureAPI: 'Texture',
  SimpleTextureBaseAPI: 'TextureBase',
  UnitHealPredictionCalculatorAPI: 'UnitHealPredictionCalculator',
};

const WIDGET_PARENTS = {
  Alpha: ['Animation'],
  AnimatableObject: ['Object'],
  Animation: ['Object'],
  AnimationGroup: ['Object'],
  ArchaeologyDigSiteFrame: ['Blob'],
  Blob: ['Frame'],
  Button: ['Frame'],
  CharacterModelBase: ['Model'],
  CheckButton: ['Button'],
  CinematicModel: ['PlayerModel'],
  ColorSelect: ['Frame'],
  ControlPoint: ['Object'],
  Cooldown: ['Frame'],
  DressUpModel: ['PlayerModel'],
  EditBox: ['Frame'],
  FlipBook: ['Animation'],
  FogOfWarFrame: ['Frame'],
  Font: ['FrameScriptObject'],
  FontString: ['Region'],
  Frame: ['Region'],
  GameTooltip: ['Frame'],
  Line: ['TextureBase'],
  LineScale: ['Scale'],
  LineTranslation: ['Translation'],
  MaskTexture: ['TextureBase'],
  MessageFrame: ['Frame'],
  Minimap: ['Frame'],
  Model: ['Frame'],
  ModelScene: ['Frame'],
  ModelSceneActor: ['ModelSceneActorBase'],
  ModelSceneActorBase: ['Object'],
  MovieFrame: ['Frame'],
  Object: ['FrameScriptObject'],
  Path: ['Animation'],
  QuestPOIFrame: ['Blob'],
  Region: ['ScriptRegion', 'ScriptRegionResizing', 'AnimatableObject'],
  Rotation: ['Animation'],
  Scale: ['Animation'],
  ScenarioPOIFrame: ['Blob'],
  ScriptRegion: ['Object'],
  ScriptRegionResizing: ['Object'],
  ScrollFrame: ['Frame'],
  SimpleHTML: ['Frame'],
  Slider: ['Frame'],
  StatusBar: ['Frame'],
  TabardModel: ['TabardModelBase'],
  TabardModelBase: ['PlayerModel'],
  Texture: ['TextureBase'],
  TextureBase: ['Region'],
  TextureCoordTranslation: ['Animation'],
  Translation: ['Animation'],
  UnitPositionFrame: ['Frame'],
  VertexColor: ['Animation'],
};

export function publicWidgetName(systemName) {
  if (WIDGET_NAMES[systemName]) return WIDGET_NAMES[systemName];
  return systemName.endsWith('API') ? systemName.slice(0, -3) : systemName;
}

export function widgetParents(widgetName) {
  return WIDGET_PARENTS[widgetName] ?? [];
}
